version: '3.4'

services:

  mysql-development:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: conexa
      MYSQL_PASSWORD: conexa!123
      MYSQL_DATABASE: agenda
    ports:
      - "3306:3306"